import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import '@gentleduck/motion/css'
import { Toaster } from '@gentleduck/registry-ui-duckui/sonner'
// import { Toaster } from './page'

// import ''
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from '@gentleduck/registry-ui-duckui/select'
import { Calendar, Clock, MicOff, Users, Video } from 'lucide-react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {process.env.NODE_ENV === 'development' && (
          <script src="https://cdn.jsdelivr.net/npm/react-scan/dist/auto.global.js" defer></script>
        )}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}>
        <Select>
          <SelectTrigger variant="outline" className="w-[230px]">
            <SelectValue placeholder="Choose a meeting" />
          </SelectTrigger>
          <SelectContent side="bottom" className="w-[230px]">
            <SelectGroup>
              <SelectLabel>Upcoming Meetings</SelectLabel>

              <SelectItem value="daily-standup">
                <div className="flex items-start gap-2">
                  <Video className="mt-1 size-4.5 text-blue-500" />
                  <div className="space-y-0.5">
                    <div className="font-medium">Daily Standup</div>
                    <div className="text-xs text-muted-foreground flex items-center gap-1">
                      <Clock className="h-3 w-3" />
                      9:00 AM - 9:15 AM
                    </div>
                  </div>
                </div>
              </SelectItem>

              <SelectItem value="team-sync">
                <div className="flex items-start gap-2">
                  <Users className="mt-1 h-4 w-4 text-green-600" />
                  <div className="space-y-0.5">
                    <div className="font-medium">Team Sync</div>
                    <div className="text-xs text-muted-foreground flex items-center gap-1">
                      <Calendar className="h-3 w-3" />
                      Tomorrow at 11:00 AM
                    </div>
                  </div>
                </div>
              </SelectItem>

              <SelectItem value="1on1">
                <div className="flex items-start gap-2">
                  <MicOff className="mt-1 h-4 w-4 text-gray-500" />
                  <div className="space-y-0.5">
                    <div className="font-medium">1-on-1 with Ahmed</div>
                    <div className="text-xs text-muted-foreground flex items-center gap-1">
                      <Clock className="h-3 w-3" />
                      2:00 PM - 2:30 PM
                    </div>
                  </div>
                </div>
              </SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
      </body>
    </html>
  )
}
