import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import '@gentleduck/motion/css'
import { Toaster } from '@gentleduck/registry-ui-duckui/sonner'
// import { Toaster } from './page'

// import ''
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from '@gentleduck/registry-ui-duckui/select'
import { Calendar, Clock, MicOff, Users, Video } from 'lucide-react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {process.env.NODE_ENV === 'development' && (
          <script src="https://cdn.jsdelivr.net/npm/react-scan/dist/auto.global.js" defer></script>
        )}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
