// @ts-nocheck
// This file is autogenerated by @gentleduck/registry-build-duckui
// Do not edit this file directly.
import * as React from 'react'

export const Index: Record<string, any> = {
  'signup-1': {
    name: 'signup-1',
    description: '',
    type: 'registry:block',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    files: [
      {
        path: 'authentication/signup-1/signup-1.constants.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentication/signup-1/signup-1.tsx',
        type: 'registry:block',
      },
    ],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentication/signup-1/signup-1')),
    source: '/registry-examples-duckui/src/authentication/signup-1',
    categories: ['authentication', 'signup-1'],
    root_folder: 'authentication/signup-1',
    chunks: [],
  },
}
