// @ts-nocheck
// This file is autogenerated by @gentleduck/registry-build-duckui
// Do not edit this file directly.
import * as React from 'react'

export const Index: Record<string, any> = {
  'signup-1': {
    name: 'signup-1',
    description: '',
    type: 'registry:block',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    files: [
      {
        path: 'authentication/signup-1/signup-1.constants.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentication/signup-1/signup-1.tsx',
        type: 'registry:block',
      },
    ],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentication/signup-1/signup-1')),
    source: '/registry-examples-duckui/src/authentication/signup-1',
    categories: ['authentication', 'signup'],
    root_folder: 'authentication/signup-1',
    chunks: [],
  },
  'login-1': {
    name: 'login-1',
    description: '',
    type: 'registry:block',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    files: [
      {
        path: 'authentication/login-1/login-1.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentication/login-1/login-form.tsx',
        type: 'registry:block',
      },
    ],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentication/login-1/login-1')),
    source: '/registry-examples-duckui/src/authentication/login-1',
    categories: ['authentication', 'login'],
    root_folder: 'authentication/login-1',
    chunks: [],
  },
  'login-2': {
    name: 'login-2',
    description: '',
    type: 'registry:block',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    files: [
      {
        path: 'authentication/login-2/login-2.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentication/login-2/login-form.tsx',
        type: 'registry:block',
      },
    ],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentication/login-2/login-2')),
    source: '/registry-examples-duckui/src/authentication/login-2',
    categories: ['authentication', 'login'],
    root_folder: 'authentication/login-2',
    chunks: [],
  },
  'login-3': {
    name: 'login-3',
    description: '',
    type: 'registry:block',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    files: [
      {
        path: 'authentication/login-3/login-3.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentication/login-3/login-form.tsx',
        type: 'registry:block',
      },
    ],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentication/login-3/login-3')),
    source: '/registry-examples-duckui/src/authentication/login-3',
    categories: ['authentication', 'login'],
    root_folder: 'authentication/login-3',
    chunks: [],
  },
  'login-4': {
    name: 'login-4',
    description: '',
    type: 'registry:block',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    files: [
      {
        path: 'authentication/login-4/login-4.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentication/login-4/login-form.tsx',
        type: 'registry:block',
      },
    ],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentication/login-4/login-4')),
    source: '/registry-examples-duckui/src/authentication/login-4',
    categories: ['authentication', 'login'],
    root_folder: 'authentication/login-4',
    chunks: [],
  },
  'login-5': {
    name: 'login-5',
    description: '',
    type: 'registry:block',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    files: [
      {
        path: 'authentication/login-5/login-5.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentication/login-5/login-form.tsx',
        type: 'registry:block',
      },
    ],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentication/login-5/login-5')),
    source: '/registry-examples-duckui/src/authentication/login-5',
    categories: ['authentication', 'login'],
    root_folder: 'authentication/login-5',
    chunks: [],
  },
}
