// @ts-nocheck
// This file is autogenerated by @gentleduck/registry-build-duckui
// Do not edit this file directly.
import * as React from 'react'

export const Index: Record<string, any> = {
  'dashboard-1': {
    categories: ['dashboards', 'dashboard'],
    chunks: [],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/dashboards/dashboard-1/dashboard-1')),
    description: '',
    files: [
      {
        path: 'dashboards/dashboard-1/dashboard-1.tsx',
        type: 'registry:block',
      },
      {
        path: 'dashboards/dashboard-1/components/app-sidebar.tsx',
        type: 'registry:block',
      },
      {
        path: 'dashboards/dashboard-1/components/chart-area-interactive.tsx',
        type: 'registry:block',
      },
      {
        path: 'dashboards/dashboard-1/components/data-table.tsx',
        type: 'registry:block',
      },
      {
        path: 'dashboards/dashboard-1/components/nav-documents.tsx',
        type: 'registry:block',
      },
      {
        path: 'dashboards/dashboard-1/components/nav-main.tsx',
        type: 'registry:block',
      },
      {
        path: 'dashboards/dashboard-1/components/nav-secondary.tsx',
        type: 'registry:block',
      },
      {
        path: 'dashboards/dashboard-1/components/nav-user.tsx',
        type: 'registry:block',
      },
      {
        path: 'dashboards/dashboard-1/components/section-cards.tsx',
        type: 'registry:block',
      },
      {
        path: 'dashboards/dashboard-1/components/site-header.tsx',
        type: 'registry:block',
      },
    ],
    name: 'dashboard-1',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    root_folder: 'dashboards/dashboard-1',
    source: '/registry-examples-duckui/src/dashboards/dashboard-1',
    type: 'registry:block',
  },
  'login-1': {
    categories: ['authentications', 'login'],
    chunks: [],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentications/login-1/login-1')),
    description: '',
    files: [
      {
        path: 'authentications/login-1/login-1.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentications/login-1/components/login-form.tsx',
        type: 'registry:block',
      },
    ],
    name: 'login-1',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    root_folder: 'authentications/login-1',
    source: '/registry-examples-duckui/src/authentications/login-1',
    type: 'registry:block',
  },
  'login-2': {
    categories: ['authentications', 'login'],
    chunks: [],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentications/login-2/login-2')),
    description: '',
    files: [
      {
        path: 'authentications/login-2/login-2.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentications/login-2/components/login-form.tsx',
        type: 'registry:block',
      },
    ],
    name: 'login-2',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    root_folder: 'authentications/login-2',
    source: '/registry-examples-duckui/src/authentications/login-2',
    type: 'registry:block',
  },
  'login-3': {
    categories: ['authentications', 'login'],
    chunks: [],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentications/login-3/login-3')),
    description: '',
    files: [
      {
        path: 'authentications/login-3/login-3.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentications/login-3/components/login-form.tsx',
        type: 'registry:block',
      },
    ],
    name: 'login-3',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    root_folder: 'authentications/login-3',
    source: '/registry-examples-duckui/src/authentications/login-3',
    type: 'registry:block',
  },
  'login-4': {
    categories: ['authentications', 'login'],
    chunks: [],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentications/login-4/login-4')),
    description: '',
    files: [
      {
        path: 'authentications/login-4/login-4.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentications/login-4/components/login-form.tsx',
        type: 'registry:block',
      },
    ],
    name: 'login-4',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    root_folder: 'authentications/login-4',
    source: '/registry-examples-duckui/src/authentications/login-4',
    type: 'registry:block',
  },
  'login-5': {
    categories: ['authentications', 'login'],
    chunks: [],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentications/login-5/login-5')),
    description: '',
    files: [
      {
        path: 'authentications/login-5/login-5.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentications/login-5/components/login-form.tsx',
        type: 'registry:block',
      },
    ],
    name: 'login-5',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    root_folder: 'authentications/login-5',
    source: '/registry-examples-duckui/src/authentications/login-5',
    type: 'registry:block',
  },
  'signup-1': {
    categories: ['authentications', 'signup'],
    chunks: [],
    component: React.lazy(() => import('@gentleduck/registry-blocks-duckui/authentications/signup-1/signup-1')),
    description: '',
    files: [
      {
        path: 'authentications/signup-1/signup-1.constants.tsx',
        type: 'registry:block',
      },
      {
        path: 'authentications/signup-1/signup-1.tsx',
        type: 'registry:block',
      },
    ],
    name: 'signup-1',
    registryDependencies: ['button', 'input', 'avatar', 'separator', 'label', 'react-hook-form'],
    root_folder: 'authentications/signup-1',
    source: '/registry-examples-duckui/src/authentications/signup-1',
    type: 'registry:block',
  },
}
