import type { RegistryEntry } from '../registry-schema'

export const registry_charts: RegistryEntry[] = [
  // Area Charts
  {
    categories: ['charts', 'charts-area'],
    files: [],
    name: 'chart-area-axes',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-area-axes',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-area'],
    files: [],
    name: 'chart-area-default',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-area-default',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-area'],
    files: [],
    name: 'chart-area-gradient',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-area-gradient',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-area'],
    files: [],
    name: 'chart-area-icons',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-area-icons',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-area'],
    files: [],
    name: 'chart-area-interactive',
    registryDependencies: ['card', 'chart', 'select'],
    root_folder: 'charts/chart-area-interactive',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-area'],
    files: [],
    name: 'chart-area-legend',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-area-legend',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-area'],
    files: [],
    name: 'chart-area-linear',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-area-linear',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-area'],
    files: [],
    name: 'chart-area-stacked-expand',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-area-stacked-expand',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-area'],
    files: [],
    name: 'chart-area-stacked',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-area-stacked',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-area'],
    files: [],
    name: 'chart-area-step',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-area-step',
    type: 'registry:block',
  },

  // Bar Charts
  {
    categories: ['charts', 'charts-bar'],
    files: [],
    name: 'chart-bar-active',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-bar-active',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-bar'],
    files: [],
    name: 'chart-bar-default',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-bar-default',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-bar'],
    files: [],
    name: 'chart-bar-horizontal',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-bar-horizontal',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-bar'],
    files: [],
    name: 'chart-bar-interactive',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-bar-interactive',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-bar'],
    files: [],
    name: 'chart-bar-label-custom',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-bar-label-custom',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-bar'],
    files: [],
    name: 'chart-bar-label',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-bar-label',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-bar'],
    files: [],
    name: 'chart-bar-mixed',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-bar-mixed',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-bar'],
    files: [],
    name: 'chart-bar-multiple',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-bar-multiple',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-bar'],
    files: [],
    name: 'chart-bar-negative',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-bar-negative',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-bar'],
    files: [],
    name: 'chart-bar-stacked',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-bar-stacked',
    type: 'registry:block',
  },

  // Line Charts
  {
    categories: ['charts', 'charts-line'],
    files: [],
    name: 'chart-line-default',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-line-default',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-line'],
    files: [],
    name: 'chart-line-dots-colors',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-line-dots-colors',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-line'],
    files: [],
    name: 'chart-line-dots-custom',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-line-dots-custom',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-line'],
    files: [],
    name: 'chart-line-dots',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-line-dots',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-line'],
    files: [],
    name: 'chart-line-interactive',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-line-interactive',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-line'],
    files: [],
    name: 'chart-line-label-custom',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-line-label-custom',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-line'],
    files: [],
    name: 'chart-line-label',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-line-label',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-line'],
    files: [],
    name: 'chart-line-linear',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-line-linear',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-line'],
    files: [],
    name: 'chart-line-multiple',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-line-multiple',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-line'],
    files: [],
    name: 'chart-line-step',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-line-step',
    type: 'registry:block',
  },

  // Pie Charts
  {
    categories: ['charts', 'charts-pie'],
    files: [],
    name: 'chart-pie-donut-active',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-pie-donut-active',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-pie'],
    files: [],
    name: 'chart-pie-donut-text',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-pie-donut-text',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-pie'],
    files: [],
    name: 'chart-pie-donut',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-pie-donut',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-pie'],
    files: [],
    name: 'chart-pie-interactive',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-pie-interactive',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-pie'],
    files: [],
    name: 'chart-pie-label-custom',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-pie-label-custom',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-pie'],
    files: [],
    name: 'chart-pie-label-list',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-pie-label-list',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-pie'],
    files: [],
    name: 'chart-pie-label',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-pie-label',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-pie'],
    files: [],
    name: 'chart-pie-legend',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-pie-legend',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-pie'],
    files: [],
    name: 'chart-pie-separator-none',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-pie-separator-none',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-pie'],
    files: [],
    name: 'chart-pie-simple',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-pie-simple',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-pie'],
    files: [],
    name: 'chart-pie-stacked',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-pie-stacked',
    type: 'registry:block',
  },

  // Radar Charts
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-default',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-default',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-dots',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-dots',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-grid-circle-fill',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-grid-circle-fill',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-grid-circle-no-lines',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-grid-circle-no-lines',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-grid-circle',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-grid-circle',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-grid-custom',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-grid-custom',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-grid-fill',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-grid-fill',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-grid-none',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-grid-none',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-icons',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-icons',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-label-custom',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-label-custom',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-legend',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-legend',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-lines-only',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-lines-only',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-multiple',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-multiple',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radar'],
    files: [],
    name: 'chart-radar-radius',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radar-radius',
    type: 'registry:block',
  },

  // Radial Charts
  {
    categories: ['charts', 'charts-radial'],
    files: [],
    name: 'chart-radial-grid',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radial-grid',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radial'],
    files: [],
    name: 'chart-radial-label',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radial-label',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radial'],
    files: [],
    name: 'chart-radial-shape',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radial-shape',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radial'],
    files: [],
    name: 'chart-radial-simple',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radial-simple',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radial'],
    files: [],
    name: 'chart-radial-stacked',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radial-stacked',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-radial'],
    files: [],
    name: 'chart-radial-text',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-radial-text',
    type: 'registry:block',
  },

  // Tooltip Variants
  {
    categories: ['charts', 'charts-tooltip'],
    files: [],
    name: 'chart-tooltip-default',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-tooltip-default',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-tooltip'],
    files: [],
    name: 'chart-tooltip-indicator-line',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-tooltip-indicator-line',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-tooltip'],
    files: [],
    name: 'chart-tooltip-indicator-none',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-tooltip-indicator-none',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-tooltip'],
    files: [],
    name: 'chart-tooltip-label-none',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-tooltip-label-none',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-tooltip'],
    files: [],
    name: 'chart-tooltip-label-custom',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-tooltip-label-custom',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-tooltip'],
    files: [],
    name: 'chart-tooltip-label-formatter',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-tooltip-label-formatter',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-tooltip'],
    files: [],
    name: 'chart-tooltip-formatter',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-tooltip-formatter',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-tooltip'],
    files: [],
    name: 'chart-tooltip-icons',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-tooltip-icons',
    type: 'registry:block',
  },
  {
    categories: ['charts', 'charts-tooltip'],
    files: [],
    name: 'chart-tooltip-advanced',
    registryDependencies: ['card', 'chart'],
    root_folder: 'charts/chart-tooltip-advanced',
    type: 'registry:block',
  },
]
