packages:
  - apps/*
  - packages/*
  - tooling/*
  - "!./apps/upload-api/"
  - "!./apps/benchmark/"

catalog:
  "@changesets/cli": ^2.29.8
  "@tabler/icons-react": 3.36.0
  "@tanstack/react-query": ^5.90.15
  "@trpc/client": ^11.8.1
  "@trpc/react-query": ^11.8.1
  "@trpc/server": ^11.8.1
  "@types/node": 22.19.3
  "@vitejs/plugin-react-swc": ^3.11.0
  "@vitest/coverage-v8": ^3.2.4
  "@vitest/ui": ^3.2.4
  husky: ^9.1.7
  lucide-react: 0.562.0
  next: ^16.1.1
  react-day-picker: ^9.8.1
  tailwindcss: 4.1.18
  tsdown: 0.18.3
  tsx: ^4.21.0
  typescript: 5.9.3
  vite: npm:rolldown-vite@^7.3.0
  vite-bundle-analyzer: ^1.3.2
  vite-plugin-inspect: ^11.3.3
  vite-tsconfig-paths: ^6.0.3
  vitest: ^4.0.16
  zod: ^4.2.1

catalogs:
  react19:
    "@types/react": ^19.2.6
    "@types/react-dom": ^19.2.3
    react: ^19.2.0
    react-dom: ^19.2.0
