packages:
  - apps/*
  - packages/*
  - tooling/*
  - '!./apps/upload-api/'
  - '!./apps/www/'
  - '!./apps/benchmark/'
  - '!packages/duck-docs/'

catalog:
  '@changesets/cli': ^2.29.3
  '@tabler/icons-react': 3.35.0
  '@tanstack/react-query': ^5.59.15
  '@trpc/client': ^11.0.0-rc.477
  '@trpc/react-query': ^11.0.0-rc.477
  '@trpc/server': ^11.0.0-rc.477
  '@types/node': 22.18.0
  '@vitejs/plugin-react-swc': ^3.11.0
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  husky: ^9.1.7
  lucide-react: 0.544.0
  next: ^15.3.1
  react-day-picker: ^9.8.1
  tailwindcss: 4.1.14
  tsdown: ^0.11
  tsx: ^4.19.4
  typescript: ^5.8.3
  vite: npm:rolldown-vite@^7.1.13
  vite-bundle-analyzer: ^0.20.1
  vite-plugin-inspect: ^11.0.1
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  zod: ^3.23.8

catalogs:
  react19:
    '@types/react': ^19.2.6
    '@types/react-dom': ^19.2.3
    react: ^19.2.0
    react-dom: ^19.2.0
