import type { Metadata } from 'next'
import './globals.css'
import '@gentleduck/motion/css'
import './mdx.css'
import { cn } from '@gentleduck/libs/cn'
import 'public/r/themes.css'
import { Toaster } from '@gentleduck/registry-ui-duckui/sonner'
import { KeyProvider } from '@gentleduck/vim/react'
import { Analytics as VercelAnalytics } from '@vercel/analytics/react'
import { TailwindIndicator } from '~/components/layouts'
import { ThemeProvider } from '~/components/providers'
import { ThemeWrapper } from '~/components/themes'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ar" dir="ltr" suppressHydrationWarning>
      <head></head>
      <body className={cn('min-h-svh bg-background font-sans antialiased duck')}>
        <KeyProvider timeoutMs={100}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            enableColorScheme>
            <ThemeWrapper>
              {
                // @ts-ignore
                <div vaul-drawer-wrapper="" aria-hidden="undefined">
                  <div className="relative flex min-h-svh flex-col bg-background">{children}</div>
                </div>
              }

              <VercelAnalytics />
              <Toaster />
              {process.env.NODE_ENV === 'development' && <TailwindIndicator />}
            </ThemeWrapper>
          </ThemeProvider>
        </KeyProvider>
      </body>
    </html>
  )
}
