import type { Registry } from '../registry-schema'

export const registry_ui: Registry = [
  {
    name: 'accordion',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather', '@gentledduck/anim'],
    registryDependencies: [],
    root_folder: 'accordion',
    files: [],
  },
  {
    name: 'alert',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather'],
    registryDependencies: [],
    root_folder: 'alert',
    files: [],
  },
  {
    name: 'alert-dialog',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'alert-dialog',
    files: [],
  },
  {
    name: 'avatar',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather'],
    registryDependencies: [],
    root_folder: 'avatar',
    files: [],
  },
  {
    name: 'badge',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather'],
    registryDependencies: [],
    root_folder: 'badge',
    files: [],
  },
  {
    name: 'button',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather'],
    registryDependencies: [],
    root_folder: 'button',
    files: [],
  },
  {
    name: 'breadcrumb',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'breadcrumb',
    files: [],
  },
  {
    name: 'command',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather'],
    registryDependencies: [],
    root_folder: 'command',
    files: [],
  },
  {
    name: 'card',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather'],
    registryDependencies: [],
    root_folder: 'card',
    files: [],
  },
  {
    name: 'dialog',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather'],
    registryDependencies: [],
    root_folder: 'dialog',
    files: [],
  },
  {
    name: 'drawer',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather'],
    registryDependencies: [],
    root_folder: 'drawer',
    files: [],
  },
  {
    name: 'input',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'input',
    files: [],
  },
  {
    name: 'label',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'label',
    files: [],
  },
  {
    name: 'progress',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'progress',
    files: [],
  },
  {
    name: 'radio-group',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'radio-group',
    files: [],
  },

  {
    name: 'scroll-area',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'scroll-area',
    files: [],
  },

  {
    name: 'separator',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'separator',
    files: [],
  },
  {
    name: 'sheet',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather'],
    registryDependencies: ['dialog'],
    root_folder: 'sheet',
    files: [],
  },
  {
    name: 'skeleton',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'skeleton',
    files: [],
  },
  {
    name: 'slider',
    type: 'registry:ui',
    dependencies: ['@gentleduck/variants'],
    registryDependencies: [],
    root_folder: 'slider',
    files: [],
  },

  {
    name: 'sonner',
    type: 'registry:ui',
    dependencies: ['sonner'],
    registryDependencies: [],
    root_folder: 'sonner',
    files: [],
  },
  {
    name: 'switch',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather'],
    registryDependencies: [],
    root_folder: 'switch',
    files: [],
  },
  {
    name: 'tabs',
    type: 'registry:ui',
    dependencies: ['@gentleduck/aria-feather '],
    registryDependencies: [],
    root_folder: 'tabs',
    files: [],
  },
  {
    name: 'textarea',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'textarea',
    files: [],
  },
  {
    name: 'toggle',
    type: 'registry:ui',
    dependencies: ['@gentleduck/variants'],
    registryDependencies: [],
    root_folder: 'toggle',
    files: [],
  },
  {
    name: 'toggle-group',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: ['toggle'],
    root_folder: 'toggle-group',
    files: [],
  },
  {
    name: 'aspect-ratio',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'aspect-ratio',
    files: [],
  },
  {
    name: 'table',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'table',
    files: [],
  },
  {
    name: 'resizable',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'resizable',
    files: [],
  },
  {
    name: 'pagination',
    type: 'registry:ui',
    registryDependencies: [],
    root_folder: 'pagination',
    files: [],
  },
  {
    name: 'checkbox',
    type: 'registry:ui',
    registryDependencies: [],
    root_folder: 'checkbox',
    files: [],
  },
  // {
  //   name: 'typography',
  //   type: 'registry:ui',
  //   dependencies: [],
  //   registryDependencies: [],
  //   root_folder: 'typography',
  //   files: [],
  // },
]
