import type { RegistryEntry } from '../registry-schema'

export const registry_ui: RegistryEntry[] = [
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/motion', '@gentleduck/libs'],
    files: [],
    name: 'accordion',
    root_folder: 'accordion',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/variants', '@gentleduck/libs'],
    files: [],
    name: 'alert',
    root_folder: 'alert',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs'],
    files: [],
    name: 'alert-dialog',
    registryDependencies: ['dialog'],
    root_folder: 'alert-dialog',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs'],
    files: [],
    name: 'aspect-ratio',
    root_folder: 'aspect-ratio',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'avatar',
    root_folder: 'avatar',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/variants', '@gentleduck/libs'],
    files: [],
    name: 'badge',
    root_folder: 'badge',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs'],
    files: [],
    name: 'breadcrumb',
    root_folder: 'breadcrumb',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/variants', '@gentleduck/libs'],
    files: [],
    name: 'button',
    root_folder: 'button',
    type: 'registry:ui',
  },
  {
    dependencies: ['react-day-picker', 'date-fns', '@gentleduck/libs'],
    files: [],
    name: 'calendar',
    registryDependencies: ['button'],
    root_folder: 'calendar',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'card',
    root_folder: 'card',
    type: 'registry:ui',
  },
  {
    dependencies: ['embla-carousel-react', '@gentleduck/libs'],
    files: [],
    name: 'carousel',
    registryDependencies: ['button'],
    root_folder: 'carousel',
    type: 'registry:ui',
  },
  {
    dependencies: ['recharts', '@gentleduck/libs'],
    files: [],
    name: 'chart',
    root_folder: 'chart',
    type: 'registry:ui',
  },

  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/motion', '@gentleduck/libs'],
    files: [],
    name: 'checkbox',
    registryDependencies: ['label'],
    root_folder: 'checkbox',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'collapsible',
    registryDependencies: ['button'],
    root_folder: 'collapsible',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/vim', '@gentleduck/libs'],
    files: [],
    name: 'command',
    registryDependencies: ['scroll-area', 'dialog'],
    root_folder: 'command',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'context-menu',
    registryDependencies: ['dropdown-menu'],
    root_folder: 'context-menu',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/motion', '@gentleduck/hooks', '@gentleduck/libs'],
    files: [],
    name: 'dialog',
    root_folder: 'dialog',
    type: 'registry:ui',
  },
  {
    dependencies: ['vaul', '@gentleduck/libs'],
    files: [],
    name: 'drawer',
    root_folder: 'drawer',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', '@gentleduck/vim'],
    files: [],
    name: 'dropdown-menu',
    registryDependencies: ['command', 'button', 'popover', 'radio-group'],
    root_folder: 'dropdown-menu',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/variants', '@gentleduck/libs', '@radix-ui/react-navigation-menu'],
    files: [],
    name: 'navigation-menu',
    registryDependencies: [],
    root_folder: 'navigation-menu',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives', 'react-hook-form', 'zod', '@hookform/resolvers'],
    files: [],
    name: 'react-hook-form',
    registryDependencies: ['label'],
    root_folder: 'react-hook-form',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/lib', '@gentleduck/primitives', '@gentleduck/motion'],
    files: [],
    name: 'hover-card',
    registryDependencies: ['button'],
    root_folder: 'hover-card',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'input',
    root_folder: 'input',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'input-otp',
    root_folder: 'input-otp',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'label',
    root_folder: 'label',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'menubar',
    registryDependencies: ['button', 'dropdown-menu'],
    root_folder: 'menubar',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'pagination',
    registryDependencies: ['button'],
    root_folder: 'pagination',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', '@gentleduck/motion'],
    files: [],
    name: 'popover',
    root_folder: 'popover',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'progress',
    root_folder: 'progress',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', '@gentleduck/motion'],
    files: [],
    name: 'radio-group',
    registryDependencies: ['label'],
    root_folder: 'radio-group',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'resizable',
    root_folder: 'resizable',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'scroll-area',
    root_folder: 'scroll-area',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs'],
    files: [],
    name: 'select',
    registryDependencies: ['command', 'button', 'popover'],
    root_folder: 'select',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'separator',
    root_folder: 'separator',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', '@gentleduck/motion', '@gentleduck/variants'],
    files: [],
    name: 'sheet',
    root_folder: 'sheet',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'skeleton',
    root_folder: 'skeleton',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs'],
    files: [],
    name: 'slider',
    root_folder: 'slider',
    type: 'registry:ui',
  },
  {
    dependencies: ['sonner', 'next-themes', '@gentleduck/libs'],
    files: [],
    name: 'sonner',
    registryDependencies: ['button', 'progress'],
    root_folder: 'sonner',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', '@gentleduck/motion'],
    files: [],
    name: 'switch',
    root_folder: 'switch',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'table',
    root_folder: 'table',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'tabs',
    registryDependencies: [],
    root_folder: 'tabs',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs'],
    files: [],
    name: 'textarea',
    root_folder: 'textarea',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/variants', '@gentleduck/libs'],
    files: [],
    name: 'toggle',
    registryDependencies: [],
    root_folder: 'toggle',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/variants', '@gentleduck/libs'],
    files: [],
    name: 'toggle-group',
    registryDependencies: ['toggle'],
    root_folder: 'toggle-group',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/motion', '@gentleduck/primitives'],
    files: [],
    name: 'tooltip',
    root_folder: 'tooltip',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/variants'],
    files: [],
    name: 'button-group',
    registryDependencies: ['button'],
    root_folder: 'button-group',
    type: 'registry:ui',
  },
]
