import path from 'node:path'
import { REGISTRY_ITEM_TYPES } from '@gentleduck/registers'
import { config } from 'dotenv'
import { envSchema } from './main.dto'

config()
export const ENV = await envSchema.parseAsync(process.env)
export const REGISTRY_PATH = path.join(process.cwd(), `../..${ENV.REGISTRY_OUTPUT_PATH}public/r/`)

export const PUBLIC_REGISTRY_PATH = path.join(REGISTRY_PATH, 'components')

export const REGISTRY_INDEX_WHITELIST = REGISTRY_ITEM_TYPES

export const tsx_index: string = `// @ts-nocheck
// This file is autogenerated by @gentleduck/registry-build-duckui 
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`
