import {
  ChartAreaAxes,
  ChartAreaDefault,
  ChartAreaGradient,
  ChartAreaIcons,
  ChartAreaInteractive,
  ChartAreaLegend,
  ChartAreaLinear,
  ChartAreaStacked,
  ChartAreaStackedExpand,
  ChartAreaStep,
  ChartBarActive,
  ChartBarDefault,
  ChartBarHorizontal,
  ChartBarInteractive,
  ChartBarLabel,
  ChartBarLabelCustom,
  ChartBarMixed,
  ChartBarMultiple,
  ChartBarNegative,
  ChartBarStacked,
  ChartLineDefault,
  ChartLineDots,
  ChartLineDotsColors,
  ChartLineDotsCustom,
  ChartLineInteractive,
  ChartLineLabel,
  ChartLineLabelCustom,
  ChartLineLinear,
  ChartLineMultiple,
  ChartLineStep,
  ChartPieDonut,
  ChartPieDonutActive,
  ChartPieDonutText,
  ChartPieInteractive,
  ChartPieLabel,
  ChartPieLabelCustom,
  ChartPieLabelList,
  ChartPieLegend,
  ChartPieSeparatorNone,
  ChartPieSimple,
  ChartPieStacked,
  ChartRadarDefault,
  ChartRadarDots,
  ChartRadarGridCircle,
  ChartRadarGridCircleFill,
  ChartRadarGridCircleNoLines,
  ChartRadarGridCustom,
  ChartRadarGridFill,
  ChartRadarGridNone,
  ChartRadarIcons,
  ChartRadarLabelCustom,
  ChartRadarLegend,
  ChartRadarLinesOnly,
  ChartRadarMultiple,
  ChartRadarRadius,
  ChartRadialGrid,
  ChartRadialLabel,
  ChartRadialShape,
  ChartRadialSimple,
  ChartRadialStacked,
  ChartRadialText,
  ChartTooltipAdvanced,
  ChartTooltipDefault,
  ChartTooltipFormatter,
  ChartTooltipIcons,
  ChartTooltipIndicatorLine,
  ChartTooltipIndicatorNone,
  ChartTooltipLabelCustom,
  ChartTooltipLabelFormatter,
  ChartTooltipLabelNone,
} from '@gentleduck/registry-blocks-duckui'

type ChartComponent = React.ComponentType

interface ChartItem {
  id: string
  component: ChartComponent
  fullWidth?: boolean
}

interface ChartGroups {
  area: ChartItem[]
  bar: ChartItem[]
  line: ChartItem[]
  pie: ChartItem[]
  radar: ChartItem[]
  radial: ChartItem[]
  tooltip: ChartItem[]
}

export const charts: ChartGroups = {
  area: [
    {
      component: ChartAreaInteractive,
      fullWidth: true,
      id: 'chart-area-interactive',
    },
    { component: ChartAreaDefault, id: 'chart-area-default' },
    { component: ChartAreaLinear, id: 'chart-area-linear' },
    { component: ChartAreaStep, id: 'chart-area-step' },
    { component: ChartAreaLegend, id: 'chart-area-legend' },
    { component: ChartAreaStacked, id: 'chart-area-stacked' },
    { component: ChartAreaStackedExpand, id: 'chart-area-stacked-expand' },
    { component: ChartAreaIcons, id: 'chart-area-icons' },
    { component: ChartAreaGradient, id: 'chart-area-gradient' },
    { component: ChartAreaAxes, id: 'chart-area-axes' },
  ],
  bar: [
    {
      component: ChartBarInteractive,
      fullWidth: true,
      id: 'chart-bar-interactive',
    },
    { component: ChartBarDefault, id: 'chart-bar-default' },
    { component: ChartBarHorizontal, id: 'chart-bar-horizontal' },
    { component: ChartBarMultiple, id: 'chart-bar-multiple' },
    { component: ChartBarStacked, id: 'chart-bar-stacked' },
    { component: ChartBarLabel, id: 'chart-bar-label' },
    { component: ChartBarLabelCustom, id: 'chart-bar-label-custom' },
    { component: ChartBarMixed, id: 'chart-bar-mixed' },
    { component: ChartBarActive, id: 'chart-bar-active' },
    { component: ChartBarNegative, id: 'chart-bar-negative' },
  ],
  line: [
    {
      component: ChartLineInteractive,
      fullWidth: true,
      id: 'chart-line-interactive',
    },
    { component: ChartLineDefault, id: 'chart-line-default' },
    { component: ChartLineLinear, id: 'chart-line-linear' },
    { component: ChartLineStep, id: 'chart-line-step' },
    { component: ChartLineMultiple, id: 'chart-line-multiple' },
    { component: ChartLineDots, id: 'chart-line-dots' },
    { component: ChartLineDotsCustom, id: 'chart-line-dots-custom' },
    { component: ChartLineDotsColors, id: 'chart-line-dots-colors' },
    { component: ChartLineLabel, id: 'chart-line-label' },
    { component: ChartLineLabelCustom, id: 'chart-line-label-custom' },
  ],
  pie: [
    { component: ChartPieSimple, id: 'chart-pie-simple' },
    { component: ChartPieSeparatorNone, id: 'chart-pie-separator-none' },
    { component: ChartPieLabel, id: 'chart-pie-label' },
    { component: ChartPieLabelCustom, id: 'chart-pie-label-custom' },
    { component: ChartPieLabelList, id: 'chart-pie-label-list' },
    { component: ChartPieLegend, id: 'chart-pie-legend' },
    { component: ChartPieDonut, id: 'chart-pie-donut' },
    { component: ChartPieDonutActive, id: 'chart-pie-donut-active' },
    { component: ChartPieDonutText, id: 'chart-pie-donut-text' },
    { component: ChartPieStacked, id: 'chart-pie-stacked' },
    { component: ChartPieInteractive, id: 'chart-pie-interactive' },
  ],
  radar: [
    { component: ChartRadarDefault, id: 'chart-radar-default' },
    { component: ChartRadarDots, id: 'chart-radar-dots' },
    { component: ChartRadarLinesOnly, id: 'chart-radar-lines-only' },
    { component: ChartRadarLabelCustom, id: 'chart-radar-label-custom' },
    { component: ChartRadarGridCustom, id: 'chart-radar-grid-custom' },
    { component: ChartRadarGridNone, id: 'chart-radar-grid-none' },
    { component: ChartRadarGridCircle, id: 'chart-radar-grid-circle' },
    {
      component: ChartRadarGridCircleNoLines,
      id: 'chart-radar-grid-circle-no-lines',
    },
    { component: ChartRadarGridCircleFill, id: 'chart-radar-grid-circle-fill' },
    { component: ChartRadarGridFill, id: 'chart-radar-grid-fill' },
    { component: ChartRadarMultiple, id: 'chart-radar-multiple' },
    { component: ChartRadarLegend, id: 'chart-radar-legend' },
    { component: ChartRadarIcons, id: 'chart-radar-icons' },
    { component: ChartRadarRadius, id: 'chart-radar-radius' },
  ],
  radial: [
    { component: ChartRadialSimple, id: 'chart-radial-simple' },
    { component: ChartRadialLabel, id: 'chart-radial-label' },
    { component: ChartRadialGrid, id: 'chart-radial-grid' },
    { component: ChartRadialText, id: 'chart-radial-text' },
    { component: ChartRadialShape, id: 'chart-radial-shape' },
    { component: ChartRadialStacked, id: 'chart-radial-stacked' },
  ],
  tooltip: [
    { component: ChartTooltipDefault, id: 'chart-tooltip-default' },
    {
      component: ChartTooltipIndicatorLine,
      id: 'chart-tooltip-indicator-line',
    },
    {
      component: ChartTooltipIndicatorNone,
      id: 'chart-tooltip-indicator-none',
    },
    { component: ChartTooltipLabelCustom, id: 'chart-tooltip-label-custom' },
    {
      component: ChartTooltipLabelFormatter,
      id: 'chart-tooltip-label-formatter',
    },
    { component: ChartTooltipLabelNone, id: 'chart-tooltip-label-none' },
    { component: ChartTooltipFormatter, id: 'chart-tooltip-formatter' },
    { component: ChartTooltipIcons, id: 'chart-tooltip-icons' },
    { component: ChartTooltipAdvanced, id: 'chart-tooltip-advanced' },
  ],
}

// Export individual components for backward compatibility
export {
  ChartAreaDefault,
  ChartAreaLinear,
  ChartAreaStep,
  ChartAreaLegend,
  ChartAreaStacked,
  ChartAreaStackedExpand,
  ChartAreaIcons,
  ChartAreaGradient,
  ChartAreaAxes,
  ChartAreaInteractive,
  ChartBarDefault,
  ChartBarHorizontal,
  ChartBarMultiple,
  ChartBarStacked,
  ChartBarLabel,
  ChartBarLabelCustom,
  ChartBarMixed,
  ChartBarActive,
  ChartBarNegative,
  ChartBarInteractive,
  ChartLineDefault,
  ChartLineLinear,
  ChartLineStep,
  ChartLineMultiple,
  ChartLineDots,
  ChartLineDotsCustom,
  ChartLineDotsColors,
  ChartLineLabel,
  ChartLineLabelCustom,
  ChartLineInteractive,
  ChartPieSimple,
  ChartPieSeparatorNone,
  ChartPieLabel,
  ChartPieLabelCustom,
  ChartPieLabelList,
  ChartPieLegend,
  ChartPieDonut,
  ChartPieDonutActive,
  ChartPieDonutText,
  ChartPieStacked,
  ChartPieInteractive,
  ChartRadarDefault,
  ChartRadarDots,
  ChartRadarLinesOnly,
  ChartRadarLabelCustom,
  ChartRadarGridCustom,
  ChartRadarGridNone,
  ChartRadarGridCircle,
  ChartRadarGridCircleNoLines,
  ChartRadarGridCircleFill,
  ChartRadarGridFill,
  ChartRadarMultiple,
  ChartRadarLegend,
  ChartRadarIcons,
  ChartRadarRadius,
  ChartRadialSimple,
  ChartRadialLabel,
  ChartRadialGrid,
  ChartRadialText,
  ChartRadialShape,
  ChartRadialStacked,
  ChartTooltipDefault,
  ChartTooltipIndicatorLine,
  ChartTooltipIndicatorNone,
  ChartTooltipLabelCustom,
  ChartTooltipLabelFormatter,
  ChartTooltipLabelNone,
  ChartTooltipFormatter,
  ChartTooltipIcons,
  ChartTooltipAdvanced,
}
