// SORTING (MULTI-COLUMN, ASC/DESC)
// FILTERING (COLUMN-BASED, GLOBAL, FUZZY)
// PAGINATION (PAGE SIZE, NAVIGATION)
// SELECTION (SINGLE, MULTI)
// ROW EXPANSION
// COLUMN VISIBILITY
// GROUPING
// COLUMN RESIZING
// DATA EXPORT (CSV/JSON)
// REACTIVE HOOKS (MANUAL OR SIGNAL-BASED)
