import type { Registry } from '../registry-schema'

export const registry_examples: Registry = [
  {
    name: 'accordion-examples',
    type: 'registry:example',
    registryDependencies: ['accordion'],
    root_folder: 'accordion',
    files: [],
  },
  {
    name: 'alert-examples',
    type: 'registry:example',
    registryDependencies: ['alert'],
    root_folder: 'alert',
    files: [],
  },
  {
    name: 'alert-dialog-examples',
    type: 'registry:example',
    registryDependencies: ['alert-dialog'],
    root_folder: 'alert-dialog',
    files: [],
  },
  {
    name: 'avatar-examples',
    type: 'registry:example',
    registryDependencies: ['avatar'],
    root_folder: 'avatar',
    files: [],
  },
  {
    name: 'badge-examples',
    type: 'registry:example',
    registryDependencies: ['badge'],
    root_folder: 'badge',
    files: [],
  },
  {
    name: 'button-examples',
    type: 'registry:example',
    registryDependencies: ['button'],
    root_folder: 'button',
    files: [],
  },
  {
    name: 'breadcrumb-examples',
    type: 'registry:example',
    registryDependencies: ['breadcrumb'],
    root_folder: 'breadcrumb',
    files: [],
  },
  {
    name: 'dialog-examples',
    type: 'registry:example',
    registryDependencies: ['dialog'],
    root_folder: 'dialog',
    files: [],
  },
  {
    name: 'command-examples',
    type: 'registry:example',
    registryDependencies: ['command'],
    root_folder: 'command',
    files: [],
  },
  {
    name: 'card-examples',
    type: 'registry:example',
    registryDependencies: ['card'],
    root_folder: 'card',
    files: [],
  },
  {
    name: 'calendar-examples',
    type: 'registry:example',
    registryDependencies: ['calendar'],
    root_folder: 'calendar',
    files: [],
  },
  {
    name: 'drawer-examples',
    type: 'registry:example',
    registryDependencies: ['drawer'],
    root_folder: 'drawer',
    files: [],
  },
  {
    name: 'hover-card-examples',
    type: 'registry:example',
    registryDependencies: ['hover-card'],
    root_folder: 'hover-card',
    files: [],
  },
  {
    name: 'input-examples',
    type: 'registry:example',
    registryDependencies: ['input'],
    root_folder: 'input',
    files: [],
  },
  {
    name: 'label-examples',
    type: 'registry:example',
    registryDependencies: ['label'],
    root_folder: 'label',
    files: [],
  },
  {
    name: 'progress-examples',
    type: 'registry:example',
    registryDependencies: ['progress'],
    root_folder: 'progress',
    files: [],
  },
  {
    name: 'radio-group-examples',
    type: 'registry:example',
    registryDependencies: ['radio-group'],
    root_folder: 'radio-group',
    files: [],
  },
  {
    name: 'scroll-area-examples',
    type: 'registry:example',
    registryDependencies: ['scroll-area'],
    root_folder: 'scroll-area',
    files: [],
  },
  {
    name: 'select-examples',
    type: 'registry:example',
    registryDependencies: ['select'],
    root_folder: 'select',
    files: [],
  },
  {
    name: 'separator-examples',
    type: 'registry:example',
    registryDependencies: ['separator'],
    root_folder: 'separator',
    files: [],
  },
  {
    name: 'sheet-examples',
    type: 'registry:example',
    registryDependencies: ['sheet'],
    root_folder: 'sheet',
    files: [],
  },
  {
    name: 'skeleton-examples',
    type: 'registry:example',
    registryDependencies: ['skeleton'],
    root_folder: 'skeleton',
    files: [],
  },
  {
    name: 'slider-examples',
    type: 'registry:example',
    registryDependencies: ['slider'],
    root_folder: 'slider',
    files: [],
  },
  {
    name: 'switch-examples',
    type: 'registry:example',
    registryDependencies: ['switch'],
    root_folder: 'switch',
    files: [],
  },
  {
    name: 'sonner-examples',
    type: 'registry:example',
    registryDependencies: ['sonner'],
    root_folder: 'sonner',
    files: [],
  },
  {
    name: 'tabs-examples',
    type: 'registry:example',
    registryDependencies: ['tabs'],
    root_folder: 'tabs',
    files: [],
  },
  {
    name: 'textarea-examples',
    type: 'registry:example',
    registryDependencies: ['textarea'],
    root_folder: 'textarea',
    files: [],
  },
  {
    name: 'toggle-examples',
    type: 'registry:example',
    registryDependencies: ['toggle'],
    root_folder: 'toggle',
    files: [],
  },
  {
    name: 'toggle-group-examples',
    type: 'registry:example',
    registryDependencies: ['toggle-group'],
    root_folder: 'toggle-group',
    files: [],
  },
  {
    name: 'tooltip-examples',
    type: 'registry:example',
    registryDependencies: ['tooltip'],
    root_folder: 'tooltip',
    files: [],
  },
  {
    name: 'aspect-ratio-examples',
    type: 'registry:example',
    registryDependencies: ['aspect-ratio'],
    root_folder: 'aspect-ratio',
    files: [],
  },
  {
    name: 'typography-examples',
    type: 'registry:example',
    registryDependencies: [],
    // registryDependencies: ['typography'],
    root_folder: 'typography',
    files: [],
  },
]
