import type { RegistryEntry } from '../registry-schema'

export const registry_examples: RegistryEntry[] = [
  {
    files: [],
    name: 'accordion-examples',
    registryDependencies: ['accordion'],
    root_folder: 'accordion',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'alert-examples',
    registryDependencies: ['alert'],
    root_folder: 'alert',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'alert-dialog-examples',
    registryDependencies: ['alert-dialog'],
    root_folder: 'alert-dialog',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'avatar-examples',
    registryDependencies: ['avatar'],
    root_folder: 'avatar',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'badge-examples',
    registryDependencies: ['badge'],
    root_folder: 'badge',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'button-examples',
    registryDependencies: ['button'],
    root_folder: 'button',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'breadcrumb-examples',
    registryDependencies: ['breadcrumb'],
    root_folder: 'breadcrumb',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'dialog-examples',
    registryDependencies: ['dialog'],
    root_folder: 'dialog',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'command-examples',
    registryDependencies: ['command'],
    root_folder: 'command',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'card-examples',
    registryDependencies: ['card'],
    root_folder: 'card',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'calendar-examples',
    registryDependencies: ['calendar'],
    root_folder: 'calendar',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'drawer-examples',
    registryDependencies: ['drawer'],
    root_folder: 'drawer',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'hover-card-examples',
    registryDependencies: ['hover-card'],
    root_folder: 'hover-card',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'input-examples',
    registryDependencies: ['input'],
    root_folder: 'input',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'label-examples',
    registryDependencies: ['label'],
    root_folder: 'label',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'progress-examples',
    registryDependencies: ['progress'],
    root_folder: 'progress',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'radio-group-examples',
    registryDependencies: ['radio-group'],
    root_folder: 'radio-group',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'scroll-area-examples',
    registryDependencies: ['scroll-area'],
    root_folder: 'scroll-area',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'select-examples',
    registryDependencies: ['select'],
    root_folder: 'select',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'separator-examples',
    registryDependencies: ['separator'],
    root_folder: 'separator',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'sheet-examples',
    registryDependencies: ['sheet'],
    root_folder: 'sheet',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'skeleton-examples',
    registryDependencies: ['skeleton'],
    root_folder: 'skeleton',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'slider-examples',
    registryDependencies: ['slider'],
    root_folder: 'slider',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'switch-examples',
    registryDependencies: ['switch'],
    root_folder: 'switch',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'sonner-examples',
    registryDependencies: ['sonner'],
    root_folder: 'sonner',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'tabs-examples',
    registryDependencies: ['tabs'],
    root_folder: 'tabs',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'textarea-examples',
    registryDependencies: ['textarea'],
    root_folder: 'textarea',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'toggle-examples',
    registryDependencies: ['toggle'],
    root_folder: 'toggle',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'toggle-group-examples',
    registryDependencies: ['toggle-group'],
    root_folder: 'toggle-group',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'tooltip-examples',
    registryDependencies: ['tooltip'],
    root_folder: 'tooltip',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'aspect-ratio-examples',
    registryDependencies: ['aspect-ratio'],
    root_folder: 'aspect-ratio',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'typography-examples',
    registryDependencies: [],
    // registryDependencies: ['typography'],
    root_folder: 'typography',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'table-examples',
    registryDependencies: ['table'],
    root_folder: 'table',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'resizable-examples',
    registryDependencies: ['resizable'],
    root_folder: 'resizable',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'pagination-examples',
    registryDependencies: ['pagination'],
    root_folder: 'pagination',
    type: 'registry:example',
  },

  {
    files: [],
    name: 'checkbox-examples',
    registryDependencies: [],
    root_folder: 'checkbox',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'carousel-examples',
    registryDependencies: ['carousel'],
    root_folder: 'carousel',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'date-picker-examples',
    registryDependencies: ['calendar', 'popover', 'button'],
    root_folder: 'date-picker',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'popover-examples',
    registryDependencies: ['popover'],
    root_folder: 'popover',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'menubar-examples',
    registryDependencies: ['menubar'],
    root_folder: 'menubar',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'dropdown-menu-examples',
    registryDependencies: ['dropdown-menu'],
    root_folder: 'dropdown-menu',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'combobox-examples',
    registryDependencies: ['popover', 'command'],
    root_folder: 'combobox',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'collapsible-examples',
    registryDependencies: ['collapsible'],
    root_folder: 'collapsible',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'input-otp-examples',
    registryDependencies: ['input-otp'],
    root_folder: 'input-otp',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'chart-examples',
    registryDependencies: ['chart'],
    root_folder: 'chart',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'navigation-menu-examples',
    registryDependencies: ['navigation-menu'],
    root_folder: 'navigation-menu',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'context-menu-examples',
    registryDependencies: ['context-menu'],
    root_folder: 'context-menu',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'data-table-examples',
    registryDependencies: ['data-table', 'table'],
    root_folder: 'data-table',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'cva-examples',
    registryDependencies: [],
    root_folder: 'cva',
    type: 'registry:example',
  },
  {
    files: [],
    name: 'button-group',
    registryDependencies: ['button-group'],
    root_folder: 'button-group',
    type: 'registry:example',
  },
]
